os: linux
dist: xenial
language: python
python:
        - 3.6.9
addons: # get google-chrome-stable
        chrome: stable
install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
        - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        - sudo apt-get update
        - sudo apt-get install google-chrome-stable
        - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
        - unzip ~/chromedriver_linux64.zip -d ~/
        - rm ~/chromedriver_linux64.zip
        - sudo mv -f ~/chromedriver /usr/local/share/
        - sudo chmod +x /usr/local/share/chromedriver
        - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
script:
        - pip install -r requirements.txt
        - pip install selenium
        - python assistop/manage.py runserver 0.0.0.0:8080 &
        - sleep 3
        - python unittests/sel_tests.py
