os: linux
dist: xenial
language: python
python:
        - 3.6.9
addons: # get google-chrome-stable
        chrome: stable
install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
        - sudo apt-get install -y libglib2.0-0 libnss3 libgconf-2-4 libfontconfig1
        - sudo apt-get update
        - wget -N https://chromedriver.storage.googleapis.com/81.0.4044.69/chromedriver_linux64.zip -P ~/
        - unzip ~/chromedriver_linux64.zip -d ~/
        - rm ~/chromedriver_linux64.zip
        - sudo mv -f ~/chromedriver /usr/local/share/
        - sudo chmod +x /usr/local/share/chromedriver
        - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
script:
        - pip install -r requirements.txt
        - pip install selenium
        - python assistop/manage.py runserver 0.0.0.0:8080 &
        - sleep 3
        - python unittests/sel_tests.py
