os: linux
dist: xenial
language: python
python:
        - 3.6.9
addons:
        firefox: "75.0"

env:
        -DJANGO=3.0.3 DB=sqlite3

before_install:
        - pip install python-coveralls
install:
        - sudo apt-get install -y libglib2.0-0 libnss3 libgconf-2-4 libfontconfig1
        - sudo apt-get update
        - wget -N https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz -P ~/
        - tar xfz ~/geckodriver-v0.24.0-linux64.tar.gz && mv -f geckodriver ~/
        - rm ~/geckodriver-v0.24.0-linux64.tar.gz
        - sudo mv -f ~/geckodriver /usr/local/share/
        - sudo chmod +x /usr/local/share/geckodriver
        - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver
script:
        - pip install -r requirements.txt
        - pip install selenium
        - cp assistop/myapp/documentation/templates/devices.json assistop/myapp/documentation/JSON/devices.json
        #- python assistop/manage.py runserver 0.0.0.0:8080 &
        - coverage run assistop/manage.py runserver 0.0.0.0:8080 & 
        - sleep 3
        #- python unittests/sel_tests.py
        - coverage run --include=unittests/sel_tests.py, unittests/sel_tests.py

after_success:
        - pip install pyyaml coveralls
        - coveralls
