#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    ports:
       - 80:80
    command: python /code/assistop/manage.py runserver 0.0.0.0:80
